# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'REI_calc_main_design.ui'
#
# Created by: PyQt5 UI code generator 5.14.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
import resources

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(799, 884)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Tabs = QtWidgets.QTabWidget(self.centralwidget)
        self.Tabs.setGeometry(QtCore.QRect(0, 0, 771, 781))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Tabs.setFont(font)
        self.Tabs.setAutoFillBackground(False)
        self.Tabs.setTabsClosable(False)
        self.Tabs.setObjectName("Tabs")
        self.Property_Tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Property_Tab.setFont(font)
        self.Property_Tab.setObjectName("Property_Tab")
        self.prop_Header = QtWidgets.QLabel(self.Property_Tab)
        self.prop_Header.setGeometry(QtCore.QRect(150, 20, 471, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.prop_Header.setFont(font)
        self.prop_Header.setObjectName("prop_Header")
        self.Logo_prop = QtWidgets.QLabel(self.Property_Tab)
        self.Logo_prop.setGeometry(QtCore.QRect(0, 0, 121, 101))
        self.Logo_prop.setText("")
        self.Logo_prop.setPixmap(QtGui.QPixmap(":/newPrefix/SFI-white.png"))
        self.Logo_prop.setScaledContents(True)
        self.Logo_prop.setObjectName("Logo_prop")
        self.formLayoutWidget = QtWidgets.QWidget(self.Property_Tab)
        self.formLayoutWidget.setGeometry(QtCore.QRect(119, 129, 501, 294))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.Property_Form = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.Property_Form.setContentsMargins(0, 10, 0, 10)
        self.Property_Form.setVerticalSpacing(10)
        self.Property_Form.setObjectName("Property_Form")
        self.Address = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Address.setFont(font)
        self.Address.setObjectName("Address")
        self.Property_Form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Address)
        self.address_Input = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.address_Input.setFont(font)
        self.address_Input.setText("")
        self.address_Input.setObjectName("address_Input")
        self.Property_Form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.address_Input)
        self.City = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.City.setFont(font)
        self.City.setObjectName("City")
        self.Property_Form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.City)
        self.city_Input = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.city_Input.setFont(font)
        self.city_Input.setObjectName("city_Input")
        self.Property_Form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.city_Input)
        self.State = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.State.setFont(font)
        self.State.setObjectName("State")
        self.Property_Form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.State)
        self.state_Input = QtWidgets.QComboBox(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.state_Input.setFont(font)
        self.state_Input.setObjectName("state_Input")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.state_Input.addItem("")
        self.Property_Form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.state_Input)
        self.ZipCode = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ZipCode.setFont(font)
        self.ZipCode.setObjectName("ZipCode")
        self.Property_Form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.ZipCode)
        self.zip_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.zip_input.setObjectName("zip_input")
        self.Property_Form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.zip_input)
        self.Taxes = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Taxes.setFont(font)
        self.Taxes.setObjectName("Taxes")
        self.Property_Form.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Taxes)
        self.taxes_Input = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.taxes_Input.setFont(font)
        self.taxes_Input.setInputMethodHints(QtCore.Qt.ImhNone)
        self.taxes_Input.setText("")
        self.taxes_Input.setObjectName("taxes_Input")
        self.Property_Form.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.taxes_Input)
        self.Landlord_Insurance = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Landlord_Insurance.setFont(font)
        self.Landlord_Insurance.setObjectName("Landlord_Insurance")
        self.Property_Form.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Landlord_Insurance)
        self.annual_insurance_input = QtWidgets.QLineEdit(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.annual_insurance_input.setFont(font)
        self.annual_insurance_input.setInputMethodHints(QtCore.Qt.ImhNone)
        self.annual_insurance_input.setText("")
        self.annual_insurance_input.setObjectName("annual_insurance_input")
        self.Property_Form.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.annual_insurance_input)
        self.Load_Images = QtWidgets.QPushButton(self.Property_Tab)
        self.Load_Images.setGeometry(QtCore.QRect(140, 430, 211, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Load_Images.setFont(font)
        self.Load_Images.setDefault(False)
        self.Load_Images.setFlat(False)
        self.Load_Images.setObjectName("Load_Images")
        self.File_Holder = QtWidgets.QListWidget(self.Property_Tab)
        self.File_Holder.setGeometry(QtCore.QRect(355, 430, 271, 181))
        self.File_Holder.setObjectName("File_Holder")
        self.Tabs.addTab(self.Property_Tab, "")
        self.Purchase_Tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Purchase_Tab.setFont(font)
        self.Purchase_Tab.setObjectName("Purchase_Tab")
        self.purch_Header = QtWidgets.QLabel(self.Purchase_Tab)
        self.purch_Header.setGeometry(QtCore.QRect(150, 20, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.purch_Header.setFont(font)
        self.purch_Header.setObjectName("purch_Header")
        self.Logo_purch = QtWidgets.QLabel(self.Purchase_Tab)
        self.Logo_purch.setGeometry(QtCore.QRect(0, 0, 121, 101))
        self.Logo_purch.setText("")
        self.Logo_purch.setPixmap(QtGui.QPixmap(":/newPrefix/SFI-white.png"))
        self.Logo_purch.setScaledContents(True)
        self.Logo_purch.setObjectName("Logo_purch")
        self.formLayoutWidget_2 = QtWidgets.QWidget(self.Purchase_Tab)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(120, 130, 501, 301))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.Purchase_Form = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.Purchase_Form.setContentsMargins(0, 5, 0, 5)
        self.Purchase_Form.setVerticalSpacing(5)
        self.Purchase_Form.setObjectName("Purchase_Form")
        self.Asking_Price = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Asking_Price.setFont(font)
        self.Asking_Price.setObjectName("Asking_Price")
        self.Purchase_Form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Asking_Price)
        self.Purchase_Price = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Purchase_Price.setFont(font)
        self.Purchase_Price.setObjectName("Purchase_Price")
        self.Purchase_Form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Purchase_Price)
        self.Fin_Rehab = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Fin_Rehab.setFont(font)
        self.Fin_Rehab.setObjectName("Fin_Rehab")
        self.Purchase_Form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Fin_Rehab)
        self.Rehab_Budget = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Rehab_Budget.setFont(font)
        self.Rehab_Budget.setObjectName("Rehab_Budget")
        self.Purchase_Form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Rehab_Budget)
        self.ARV = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.ARV.setFont(font)
        self.ARV.setObjectName("ARV")
        self.Purchase_Form.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.ARV)
        self.Closing_Costs = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Closing_Costs.setFont(font)
        self.Closing_Costs.setObjectName("Closing_Costs")
        self.Purchase_Form.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Closing_Costs)
        self.Emergency_Fund = QtWidgets.QLabel(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Emergency_Fund.setFont(font)
        self.Emergency_Fund.setObjectName("Emergency_Fund")
        self.Purchase_Form.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Emergency_Fund)
        self.asking_price_input = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.asking_price_input.setFont(font)
        self.asking_price_input.setObjectName("asking_price_input")
        self.Purchase_Form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.asking_price_input)
        self.purchase_price_input = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.purchase_price_input.setFont(font)
        self.purchase_price_input.setObjectName("purchase_price_input")
        self.Purchase_Form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.purchase_price_input)
        self.fin_rehab_logical = QtWidgets.QComboBox(self.formLayoutWidget_2)
        self.fin_rehab_logical.setObjectName("fin_rehab_logical")
        self.fin_rehab_logical.addItem("")
        self.fin_rehab_logical.addItem("")
        self.Purchase_Form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.fin_rehab_logical)
        self.rehab_budget_input = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.rehab_budget_input.setFont(font)
        self.rehab_budget_input.setObjectName("rehab_budget_input")
        self.Purchase_Form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.rehab_budget_input)
        self.arv_input = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.arv_input.setFont(font)
        self.arv_input.setObjectName("arv_input")
        self.Purchase_Form.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.arv_input)
        self.closing_costs_input = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.closing_costs_input.setFont(font)
        self.closing_costs_input.setObjectName("closing_costs_input")
        self.Purchase_Form.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.closing_costs_input)
        self.emerg_fund_input = QtWidgets.QLineEdit(self.formLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.emerg_fund_input.setFont(font)
        self.emerg_fund_input.setObjectName("emerg_fund_input")
        self.Purchase_Form.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.emerg_fund_input)
        self.Financing_subheader = QtWidgets.QLabel(self.Purchase_Tab)
        self.Financing_subheader.setGeometry(QtCore.QRect(120, 340, 141, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Financing_subheader.setFont(font)
        self.Financing_subheader.setObjectName("Financing_subheader")
        self.Purchase_subheader = QtWidgets.QLabel(self.Purchase_Tab)
        self.Purchase_subheader.setGeometry(QtCore.QRect(120, 110, 91, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Purchase_subheader.setFont(font)
        self.Purchase_subheader.setObjectName("Purchase_subheader")
        self.Tabs.addTab(self.Purchase_Tab, "")
        self.Income_Tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Income_Tab.setFont(font)
        self.Income_Tab.setObjectName("Income_Tab")
        self.income_Header = QtWidgets.QLabel(self.Income_Tab)
        self.income_Header.setGeometry(QtCore.QRect(150, 20, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.income_Header.setFont(font)
        self.income_Header.setObjectName("income_Header")
        self.Logo_income = QtWidgets.QLabel(self.Income_Tab)
        self.Logo_income.setGeometry(QtCore.QRect(0, 0, 121, 101))
        self.Logo_income.setText("")
        self.Logo_income.setPixmap(QtGui.QPixmap(":/newPrefix/SFI-white.png"))
        self.Logo_income.setScaledContents(True)
        self.Logo_income.setObjectName("Logo_income")
        self.formLayoutWidget_3 = QtWidgets.QWidget(self.Income_Tab)
        self.formLayoutWidget_3.setGeometry(QtCore.QRect(120, 130, 501, 245))
        self.formLayoutWidget_3.setObjectName("formLayoutWidget_3")
        self.Income_Form = QtWidgets.QFormLayout(self.formLayoutWidget_3)
        self.Income_Form.setContentsMargins(0, 10, 0, 10)
        self.Income_Form.setVerticalSpacing(10)
        self.Income_Form.setObjectName("Income_Form")
        self.Num_Units = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Num_Units.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Num_Units.setObjectName("Num_Units")
        self.Income_Form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Num_Units)
        self.Ave_Rent_Unit = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Ave_Rent_Unit.setObjectName("Ave_Rent_Unit")
        self.Income_Form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Ave_Rent_Unit)
        self.num_units_input = QtWidgets.QSpinBox(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.num_units_input.setFont(font)
        self.num_units_input.setMinimum(1)
        self.num_units_input.setMaximum(200)
        self.num_units_input.setObjectName("num_units_input")
        self.Income_Form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.num_units_input)
        self.ave_rent_input = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.ave_rent_input.setFont(font)
        self.ave_rent_input.setObjectName("ave_rent_input")
        self.Income_Form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.ave_rent_input)
        self.Total_Rent_Month = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Total_Rent_Month.setObjectName("Total_Rent_Month")
        self.Income_Form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Total_Rent_Month)
        self.tot_rent_month_auto = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.tot_rent_month_auto.setFont(font)
        self.tot_rent_month_auto.setReadOnly(True)
        self.tot_rent_month_auto.setObjectName("tot_rent_month_auto")
        self.Income_Form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.tot_rent_month_auto)
        self.Other_Income_Month = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Other_Income_Month.setObjectName("Other_Income_Month")
        self.Income_Form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Other_Income_Month)
        self.other_income_month_input = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.other_income_month_input.setFont(font)
        self.other_income_month_input.setObjectName("other_income_month_input")
        self.Income_Form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.other_income_month_input)
        self.tot_income_month_auto = QtWidgets.QLineEdit(self.formLayoutWidget_3)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.tot_income_month_auto.setFont(font)
        self.tot_income_month_auto.setReadOnly(True)
        self.tot_income_month_auto.setObjectName("tot_income_month_auto")
        self.Income_Form.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.tot_income_month_auto)
        self.Total_Income_Month = QtWidgets.QLabel(self.formLayoutWidget_3)
        self.Total_Income_Month.setObjectName("Total_Income_Month")
        self.Income_Form.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Total_Income_Month)
        self.Tabs.addTab(self.Income_Tab, "")
        self.Expense_Tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Expense_Tab.setFont(font)
        self.Expense_Tab.setObjectName("Expense_Tab")
        self.expense_Header = QtWidgets.QLabel(self.Expense_Tab)
        self.expense_Header.setGeometry(QtCore.QRect(150, 20, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.expense_Header.setFont(font)
        self.expense_Header.setObjectName("expense_Header")
        self.Logo_exp = QtWidgets.QLabel(self.Expense_Tab)
        self.Logo_exp.setGeometry(QtCore.QRect(0, 0, 121, 101))
        self.Logo_exp.setText("")
        self.Logo_exp.setPixmap(QtGui.QPixmap(":/newPrefix/SFI-white.png"))
        self.Logo_exp.setScaledContents(True)
        self.Logo_exp.setObjectName("Logo_exp")
        self.formLayoutWidget_5 = QtWidgets.QWidget(self.Expense_Tab)
        self.formLayoutWidget_5.setGeometry(QtCore.QRect(90, 130, 281, 433))
        self.formLayoutWidget_5.setObjectName("formLayoutWidget_5")
        self.Expense_Fixed_Form = QtWidgets.QFormLayout(self.formLayoutWidget_5)
        self.Expense_Fixed_Form.setContentsMargins(0, 10, 0, 10)
        self.Expense_Fixed_Form.setVerticalSpacing(10)
        self.Expense_Fixed_Form.setObjectName("Expense_Fixed_Form")
        self.R_and_M_Perc_2 = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.R_and_M_Perc_2.setFont(font)
        self.R_and_M_Perc_2.setObjectName("R_and_M_Perc_2")
        self.Expense_Fixed_Form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.R_and_M_Perc_2)
        self.tot_fixed_exp_auto = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.tot_fixed_exp_auto.setFont(font)
        self.tot_fixed_exp_auto.setReadOnly(True)
        self.tot_fixed_exp_auto.setObjectName("tot_fixed_exp_auto")
        self.Expense_Fixed_Form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tot_fixed_exp_auto)
        self.Electric = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Electric.setFont(font)
        self.Electric.setObjectName("Electric")
        self.Expense_Fixed_Form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Electric)
        self.electric_input = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.electric_input.setFont(font)
        self.electric_input.setObjectName("electric_input")
        self.Expense_Fixed_Form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.electric_input)
        self.Water_and_Sewer = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Water_and_Sewer.setFont(font)
        self.Water_and_Sewer.setObjectName("Water_and_Sewer")
        self.Expense_Fixed_Form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Water_and_Sewer)
        self.w_and_s_input = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.w_and_s_input.setFont(font)
        self.w_and_s_input.setObjectName("w_and_s_input")
        self.Expense_Fixed_Form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.w_and_s_input)
        self.PMI = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.PMI.setFont(font)
        self.PMI.setObjectName("PMI")
        self.Expense_Fixed_Form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.PMI)
        self.pmi_input = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.pmi_input.setFont(font)
        self.pmi_input.setObjectName("pmi_input")
        self.Expense_Fixed_Form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pmi_input)
        self.Garbage = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Garbage.setFont(font)
        self.Garbage.setObjectName("Garbage")
        self.Expense_Fixed_Form.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Garbage)
        self.garbage_input = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.garbage_input.setFont(font)
        self.garbage_input.setObjectName("garbage_input")
        self.Expense_Fixed_Form.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.garbage_input)
        self.HOA = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.HOA.setFont(font)
        self.HOA.setObjectName("HOA")
        self.Expense_Fixed_Form.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.HOA)
        self.hoa_input = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.hoa_input.setFont(font)
        self.hoa_input.setObjectName("hoa_input")
        self.Expense_Fixed_Form.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.hoa_input)
        self.Taxes_Monthly = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Taxes_Monthly.setFont(font)
        self.Taxes_Monthly.setObjectName("Taxes_Monthly")
        self.Expense_Fixed_Form.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Taxes_Monthly)
        self.monthly_taxes_auto = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.monthly_taxes_auto.setFont(font)
        self.monthly_taxes_auto.setReadOnly(True)
        self.monthly_taxes_auto.setObjectName("monthly_taxes_auto")
        self.Expense_Fixed_Form.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.monthly_taxes_auto)
        self.Insurance = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Insurance.setFont(font)
        self.Insurance.setObjectName("Insurance")
        self.Expense_Fixed_Form.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Insurance)
        self.insurance_auto = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.insurance_auto.setFont(font)
        self.insurance_auto.setReadOnly(True)
        self.insurance_auto.setObjectName("insurance_auto")
        self.Expense_Fixed_Form.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.insurance_auto)
        self.Other_Expenses = QtWidgets.QLabel(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Other_Expenses.setFont(font)
        self.Other_Expenses.setObjectName("Other_Expenses")
        self.Expense_Fixed_Form.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.Other_Expenses)
        self.other_input = QtWidgets.QLineEdit(self.formLayoutWidget_5)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.other_input.setFont(font)
        self.other_input.setObjectName("other_input")
        self.Expense_Fixed_Form.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.other_input)
        self.Fixed_Subheader = QtWidgets.QLabel(self.Expense_Tab)
        self.Fixed_Subheader.setGeometry(QtCore.QRect(90, 110, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Fixed_Subheader.setFont(font)
        self.Fixed_Subheader.setObjectName("Fixed_Subheader")
        self.Variable_Subheader = QtWidgets.QLabel(self.Expense_Tab)
        self.Variable_Subheader.setGeometry(QtCore.QRect(370, 110, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Variable_Subheader.setFont(font)
        self.Variable_Subheader.setObjectName("Variable_Subheader")
        self.formLayoutWidget_7 = QtWidgets.QWidget(self.Expense_Tab)
        self.formLayoutWidget_7.setGeometry(QtCore.QRect(370, 132, 381, 433))
        self.formLayoutWidget_7.setObjectName("formLayoutWidget_7")
        self.Expense_Var_Form = QtWidgets.QFormLayout(self.formLayoutWidget_7)
        self.Expense_Var_Form.setContentsMargins(0, 10, 0, 10)
        self.Expense_Var_Form.setVerticalSpacing(10)
        self.Expense_Var_Form.setObjectName("Expense_Var_Form")
        self.Total_Var_Expense = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Total_Var_Expense.setFont(font)
        self.Total_Var_Expense.setObjectName("Total_Var_Expense")
        self.Expense_Var_Form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Total_Var_Expense)
        self.tot_var_exp_auto = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.tot_var_exp_auto.setFont(font)
        self.tot_var_exp_auto.setReadOnly(True)
        self.tot_var_exp_auto.setObjectName("tot_var_exp_auto")
        self.Expense_Var_Form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.tot_var_exp_auto)
        self.R_and_M_Perc = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.R_and_M_Perc.setFont(font)
        self.R_and_M_Perc.setObjectName("R_and_M_Perc")
        self.Expense_Var_Form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.R_and_M_Perc)
        self.r_and_m_input = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.r_and_m_input.setFont(font)
        self.r_and_m_input.setObjectName("r_and_m_input")
        self.Expense_Var_Form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.r_and_m_input)
        self.R_and_M_Doll = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.R_and_M_Doll.setFont(font)
        self.R_and_M_Doll.setObjectName("R_and_M_Doll")
        self.Expense_Var_Form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.R_and_M_Doll)
        self.r_and_m_auto = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.r_and_m_auto.setFont(font)
        self.r_and_m_auto.setReadOnly(True)
        self.r_and_m_auto.setObjectName("r_and_m_auto")
        self.Expense_Var_Form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.r_and_m_auto)
        self.Cap_Ex_Perc = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Cap_Ex_Perc.setFont(font)
        self.Cap_Ex_Perc.setObjectName("Cap_Ex_Perc")
        self.Expense_Var_Form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Cap_Ex_Perc)
        self.cap_ex_input = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.cap_ex_input.setFont(font)
        self.cap_ex_input.setObjectName("cap_ex_input")
        self.Expense_Var_Form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.cap_ex_input)
        self.Cap_Ex_Doll = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Cap_Ex_Doll.setFont(font)
        self.Cap_Ex_Doll.setObjectName("Cap_Ex_Doll")
        self.Expense_Var_Form.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Cap_Ex_Doll)
        self.cap_ex_auto = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.cap_ex_auto.setFont(font)
        self.cap_ex_auto.setReadOnly(True)
        self.cap_ex_auto.setObjectName("cap_ex_auto")
        self.Expense_Var_Form.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.cap_ex_auto)
        self.Vacancy_Perc = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Vacancy_Perc.setFont(font)
        self.Vacancy_Perc.setObjectName("Vacancy_Perc")
        self.Expense_Var_Form.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.Vacancy_Perc)
        self.vacancy_input = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.vacancy_input.setFont(font)
        self.vacancy_input.setObjectName("vacancy_input")
        self.Expense_Var_Form.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.vacancy_input)
        self.Vacancy_Doll = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Vacancy_Doll.setFont(font)
        self.Vacancy_Doll.setObjectName("Vacancy_Doll")
        self.Expense_Var_Form.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.Vacancy_Doll)
        self.vacancy_auto = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.vacancy_auto.setFont(font)
        self.vacancy_auto.setReadOnly(True)
        self.vacancy_auto.setObjectName("vacancy_auto")
        self.Expense_Var_Form.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.vacancy_auto)
        self.Management_Perc = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Management_Perc.setFont(font)
        self.Management_Perc.setObjectName("Management_Perc")
        self.Expense_Var_Form.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.Management_Perc)
        self.manag_input = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.manag_input.setFont(font)
        self.manag_input.setObjectName("manag_input")
        self.Expense_Var_Form.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.manag_input)
        self.Management_Doll = QtWidgets.QLabel(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Management_Doll.setFont(font)
        self.Management_Doll.setObjectName("Management_Doll")
        self.Expense_Var_Form.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.Management_Doll)
        self.manag_auto = QtWidgets.QLineEdit(self.formLayoutWidget_7)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.manag_auto.setFont(font)
        self.manag_auto.setReadOnly(True)
        self.manag_auto.setObjectName("manag_auto")
        self.Expense_Var_Form.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.manag_auto)
        self.Tabs.addTab(self.Expense_Tab, "")
        self.Assumptions_Tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Assumptions_Tab.setFont(font)
        self.Assumptions_Tab.setObjectName("Assumptions_Tab")
        self.assumptions_Header = QtWidgets.QLabel(self.Assumptions_Tab)
        self.assumptions_Header.setGeometry(QtCore.QRect(150, 20, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.assumptions_Header.setFont(font)
        self.assumptions_Header.setObjectName("assumptions_Header")
        self.Logo_assumptions = QtWidgets.QLabel(self.Assumptions_Tab)
        self.Logo_assumptions.setGeometry(QtCore.QRect(0, 0, 121, 101))
        self.Logo_assumptions.setText("")
        self.Logo_assumptions.setPixmap(QtGui.QPixmap(":/newPrefix/SFI-white.png"))
        self.Logo_assumptions.setScaledContents(True)
        self.Logo_assumptions.setObjectName("Logo_assumptions")
        self.formLayoutWidget_6 = QtWidgets.QWidget(self.Assumptions_Tab)
        self.formLayoutWidget_6.setGeometry(QtCore.QRect(120, 130, 501, 198))
        self.formLayoutWidget_6.setObjectName("formLayoutWidget_6")
        self.Assumptions_Form = QtWidgets.QFormLayout(self.formLayoutWidget_6)
        self.Assumptions_Form.setContentsMargins(0, 10, 0, 10)
        self.Assumptions_Form.setVerticalSpacing(10)
        self.Assumptions_Form.setObjectName("Assumptions_Form")
        self.Annual_Rent_Appreciation = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Annual_Rent_Appreciation.setFont(font)
        self.Annual_Rent_Appreciation.setObjectName("Annual_Rent_Appreciation")
        self.Assumptions_Form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Annual_Rent_Appreciation)
        self.Annual_Expense_Appreciation = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Annual_Expense_Appreciation.setFont(font)
        self.Annual_Expense_Appreciation.setObjectName("Annual_Expense_Appreciation")
        self.Assumptions_Form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Annual_Expense_Appreciation)
        self.Annual_Property_Appreciation = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Annual_Property_Appreciation.setFont(font)
        self.Annual_Property_Appreciation.setObjectName("Annual_Property_Appreciation")
        self.Assumptions_Form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Annual_Property_Appreciation)
        self.Selling_Costs = QtWidgets.QLabel(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Selling_Costs.setFont(font)
        self.Selling_Costs.setObjectName("Selling_Costs")
        self.Assumptions_Form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Selling_Costs)
        self.rent_appreciation_input = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.rent_appreciation_input.setFont(font)
        self.rent_appreciation_input.setObjectName("rent_appreciation_input")
        self.Assumptions_Form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.rent_appreciation_input)
        self.exp_appreciation_input = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.exp_appreciation_input.setFont(font)
        self.exp_appreciation_input.setObjectName("exp_appreciation_input")
        self.Assumptions_Form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.exp_appreciation_input)
        self.prop_appreciation_input = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.prop_appreciation_input.setFont(font)
        self.prop_appreciation_input.setObjectName("prop_appreciation_input")
        self.Assumptions_Form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.prop_appreciation_input)
        self.selling_costs_input = QtWidgets.QLineEdit(self.formLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.selling_costs_input.setFont(font)
        self.selling_costs_input.setObjectName("selling_costs_input")
        self.Assumptions_Form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.selling_costs_input)
        self.Tabs.addTab(self.Assumptions_Tab, "")
        self.Report_Tab = QtWidgets.QWidget()
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        self.Report_Tab.setFont(font)
        self.Report_Tab.setObjectName("Report_Tab")
        self.report_Header = QtWidgets.QLabel(self.Report_Tab)
        self.report_Header.setGeometry(QtCore.QRect(150, 20, 371, 51))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(30)
        font.setBold(True)
        font.setWeight(75)
        self.report_Header.setFont(font)
        self.report_Header.setObjectName("report_Header")
        self.Logo_report = QtWidgets.QLabel(self.Report_Tab)
        self.Logo_report.setGeometry(QtCore.QRect(0, 0, 121, 101))
        self.Logo_report.setText("")
        self.Logo_report.setPixmap(QtGui.QPixmap(":/newPrefix/SFI-white.png"))
        self.Logo_report.setScaledContents(True)
        self.Logo_report.setObjectName("Logo_report")
        self.Report_Progress = QtWidgets.QProgressBar(self.Report_Tab)
        self.Report_Progress.setGeometry(QtCore.QRect(120, 180, 491, 23))
        self.Report_Progress.setAutoFillBackground(True)
        self.Report_Progress.setProperty("value", 0)
        self.Report_Progress.setObjectName("Report_Progress")
        self.Generate_Report = QtWidgets.QPushButton(self.Report_Tab)
        self.Generate_Report.setGeometry(QtCore.QRect(110, 120, 251, 41))
        self.Generate_Report.setObjectName("Generate_Report")
        self.Tabs.addTab(self.Report_Tab, "")
        self.formLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget_4.setGeometry(QtCore.QRect(120, 480, 501, 281))
        self.formLayoutWidget_4.setObjectName("formLayoutWidget_4")
        self.Financing_Form = QtWidgets.QFormLayout(self.formLayoutWidget_4)
        self.Financing_Form.setContentsMargins(0, 5, 0, 5)
        self.Financing_Form.setVerticalSpacing(5)
        self.Financing_Form.setObjectName("Financing_Form")
        self.Downpayment_Perc = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Downpayment_Perc.setFont(font)
        self.Downpayment_Perc.setObjectName("Downpayment_Perc")
        self.Financing_Form.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.Downpayment_Perc)
        self.Downpayment_Doll = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Downpayment_Doll.setFont(font)
        self.Downpayment_Doll.setObjectName("Downpayment_Doll")
        self.Financing_Form.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.Downpayment_Doll)
        self.Loan_Amount = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Loan_Amount.setFont(font)
        self.Loan_Amount.setObjectName("Loan_Amount")
        self.Financing_Form.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.Loan_Amount)
        self.Interest_Rate = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Interest_Rate.setFont(font)
        self.Interest_Rate.setObjectName("Interest_Rate")
        self.Financing_Form.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.Interest_Rate)
        self.downpayment_percentage_input = QtWidgets.QSpinBox(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.downpayment_percentage_input.setFont(font)
        self.downpayment_percentage_input.setMaximum(100)
        self.downpayment_percentage_input.setProperty("value", 20)
        self.downpayment_percentage_input.setObjectName("downpayment_percentage_input")
        self.Financing_Form.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.downpayment_percentage_input)
        self.Term = QtWidgets.QLabel(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.Term.setFont(font)
        self.Term.setObjectName("Term")
        self.Financing_Form.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.Term)
        self.dp_dollar_auto = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.dp_dollar_auto.setFont(font)
        self.dp_dollar_auto.setText("")
        self.dp_dollar_auto.setReadOnly(True)
        self.dp_dollar_auto.setObjectName("dp_dollar_auto")
        self.Financing_Form.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.dp_dollar_auto)
        self.loan_amount_auto = QtWidgets.QLineEdit(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.loan_amount_auto.setFont(font)
        self.loan_amount_auto.setReadOnly(True)
        self.loan_amount_auto.setObjectName("loan_amount_auto")
        self.Financing_Form.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.loan_amount_auto)
        self.int_rate_input = QtWidgets.QDoubleSpinBox(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.int_rate_input.setFont(font)
        self.int_rate_input.setMaximum(20.99)
        self.int_rate_input.setProperty("value", 4.5)
        self.int_rate_input.setObjectName("int_rate_input")
        self.Financing_Form.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.int_rate_input)
        self.term_input = QtWidgets.QSpinBox(self.formLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        self.term_input.setFont(font)
        self.term_input.setMaximum(50)
        self.term_input.setProperty("value", 30)
        self.term_input.setObjectName("term_input")
        self.Financing_Form.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.term_input)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 799, 31))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuAbout = QtWidgets.QMenu(self.menubar)
        self.menuAbout.setObjectName("menuAbout")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionLoad = QtWidgets.QAction(MainWindow)
        self.actionLoad.setObjectName("actionLoad")
        self.actionSave = QtWidgets.QAction(MainWindow)
        self.actionSave.setObjectName("actionSave")
        self.actionSave_As = QtWidgets.QAction(MainWindow)
        self.actionSave_As.setObjectName("actionSave_As")
        self.actionExecute = QtWidgets.QAction(MainWindow)
        self.actionExecute.setObjectName("actionExecute")
        self.actionSend = QtWidgets.QAction(MainWindow)
        self.actionSend.setObjectName("actionSend")
        self.actionClear_All = QtWidgets.QAction(MainWindow)
        self.actionClear_All.setObjectName("actionClear_All")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout_REI_Calculator = QtWidgets.QAction(MainWindow)
        self.actionAbout_REI_Calculator.setObjectName("actionAbout_REI_Calculator")
        self.actionSFI = QtWidgets.QAction(MainWindow)
        self.actionSFI.setObjectName("actionSFI")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionLoad)
        self.menuFile.addAction(self.actionSave)
        self.menuFile.addAction(self.actionSave_As)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExecute)
        self.menuFile.addAction(self.actionSend)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionClear_All)
        self.menuFile.addAction(self.actionExit)
        self.menuAbout.addAction(self.actionAbout_REI_Calculator)
        self.menuAbout.addAction(self.actionSFI)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        self.Tabs.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.prop_Header.setText(_translate("MainWindow", "Property Information"))
        self.Address.setText(_translate("MainWindow", "Property Address: "))
        self.address_Input.setPlaceholderText(_translate("MainWindow", "enter address"))
        self.City.setText(_translate("MainWindow", "City:"))
        self.city_Input.setPlaceholderText(_translate("MainWindow", "city"))
        self.State.setText(_translate("MainWindow", "State:"))
        self.state_Input.setItemText(0, _translate("MainWindow", "AK"))
        self.state_Input.setItemText(1, _translate("MainWindow", "AL"))
        self.state_Input.setItemText(2, _translate("MainWindow", "AR"))
        self.state_Input.setItemText(3, _translate("MainWindow", "AS"))
        self.state_Input.setItemText(4, _translate("MainWindow", "AZ"))
        self.state_Input.setItemText(5, _translate("MainWindow", "CA"))
        self.state_Input.setItemText(6, _translate("MainWindow", "CO"))
        self.state_Input.setItemText(7, _translate("MainWindow", "CT"))
        self.state_Input.setItemText(8, _translate("MainWindow", "DC"))
        self.state_Input.setItemText(9, _translate("MainWindow", "DE"))
        self.state_Input.setItemText(10, _translate("MainWindow", "FL"))
        self.state_Input.setItemText(11, _translate("MainWindow", "GA"))
        self.state_Input.setItemText(12, _translate("MainWindow", "HI"))
        self.state_Input.setItemText(13, _translate("MainWindow", "IA"))
        self.state_Input.setItemText(14, _translate("MainWindow", "ID"))
        self.state_Input.setItemText(15, _translate("MainWindow", "IL"))
        self.state_Input.setItemText(16, _translate("MainWindow", "IN"))
        self.state_Input.setItemText(17, _translate("MainWindow", "KS"))
        self.state_Input.setItemText(18, _translate("MainWindow", "KY"))
        self.state_Input.setItemText(19, _translate("MainWindow", "LA"))
        self.state_Input.setItemText(20, _translate("MainWindow", "MA"))
        self.state_Input.setItemText(21, _translate("MainWindow", "ME"))
        self.state_Input.setItemText(22, _translate("MainWindow", "MD"))
        self.state_Input.setItemText(23, _translate("MainWindow", "MI"))
        self.state_Input.setItemText(24, _translate("MainWindow", "MN"))
        self.state_Input.setItemText(25, _translate("MainWindow", "MO"))
        self.state_Input.setItemText(26, _translate("MainWindow", "MS"))
        self.state_Input.setItemText(27, _translate("MainWindow", "MT"))
        self.state_Input.setItemText(28, _translate("MainWindow", "NC"))
        self.state_Input.setItemText(29, _translate("MainWindow", "ND"))
        self.state_Input.setItemText(30, _translate("MainWindow", "NE"))
        self.state_Input.setItemText(31, _translate("MainWindow", "NH"))
        self.state_Input.setItemText(32, _translate("MainWindow", "NJ"))
        self.state_Input.setItemText(33, _translate("MainWindow", "NM"))
        self.state_Input.setItemText(34, _translate("MainWindow", "NV"))
        self.state_Input.setItemText(35, _translate("MainWindow", "NY"))
        self.state_Input.setItemText(36, _translate("MainWindow", "OH"))
        self.state_Input.setItemText(37, _translate("MainWindow", "OK"))
        self.state_Input.setItemText(38, _translate("MainWindow", "OR"))
        self.state_Input.setItemText(39, _translate("MainWindow", "PA"))
        self.state_Input.setItemText(40, _translate("MainWindow", "PR"))
        self.state_Input.setItemText(41, _translate("MainWindow", "RI"))
        self.state_Input.setItemText(42, _translate("MainWindow", "SC"))
        self.state_Input.setItemText(43, _translate("MainWindow", "SD"))
        self.state_Input.setItemText(44, _translate("MainWindow", "TN"))
        self.state_Input.setItemText(45, _translate("MainWindow", "TX"))
        self.state_Input.setItemText(46, _translate("MainWindow", "UT"))
        self.state_Input.setItemText(47, _translate("MainWindow", "VA"))
        self.state_Input.setItemText(48, _translate("MainWindow", "VI"))
        self.state_Input.setItemText(49, _translate("MainWindow", "VT"))
        self.state_Input.setItemText(50, _translate("MainWindow", "WA"))
        self.state_Input.setItemText(51, _translate("MainWindow", "WI"))
        self.state_Input.setItemText(52, _translate("MainWindow", "WV"))
        self.state_Input.setItemText(53, _translate("MainWindow", "WY"))
        self.ZipCode.setText(_translate("MainWindow", "Zip Code:"))
        self.zip_input.setPlaceholderText(_translate("MainWindow", "zip code"))
        self.Taxes.setText(_translate("MainWindow", "Prior Year\'s Taxes ($):"))
        self.taxes_Input.setPlaceholderText(_translate("MainWindow", "annual property tax"))
        self.Landlord_Insurance.setText(_translate("MainWindow", "Landlord Insurance ($):"))
        self.annual_insurance_input.setPlaceholderText(_translate("MainWindow", "annual insurance"))
        self.Load_Images.setAccessibleDescription(_translate("MainWindow", "<html><head/><body><p>Click to load images into the report.</p></body></html>"))
        self.Load_Images.setText(_translate("MainWindow", "Property Images"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Property_Tab), _translate("MainWindow", "Property"))
        self.purch_Header.setText(_translate("MainWindow", "Purchase Information"))
        self.Asking_Price.setText(_translate("MainWindow", "Asking Price ($):"))
        self.Purchase_Price.setText(_translate("MainWindow", "Purchase Price ($):"))
        self.Fin_Rehab.setText(_translate("MainWindow", "Financing Rehab:"))
        self.Rehab_Budget.setText(_translate("MainWindow", "Rehab Budget ($):"))
        self.ARV.setText(_translate("MainWindow", "ARV ($):"))
        self.Closing_Costs.setText(_translate("MainWindow", "Closing Costs ($):"))
        self.Emergency_Fund.setText(_translate("MainWindow", "Emergency Fund ($):"))
        self.asking_price_input.setPlaceholderText(_translate("MainWindow", "initial asking price"))
        self.purchase_price_input.setPlaceholderText(_translate("MainWindow", "purchase price"))
        self.fin_rehab_logical.setItemText(0, _translate("MainWindow", "Yes"))
        self.fin_rehab_logical.setItemText(1, _translate("MainWindow", "No"))
        self.rehab_budget_input.setPlaceholderText(_translate("MainWindow", "rehab budget"))
        self.arv_input.setPlaceholderText(_translate("MainWindow", "estimated ARV"))
        self.closing_costs_input.setPlaceholderText(_translate("MainWindow", "closing costs"))
        self.emerg_fund_input.setPlaceholderText(_translate("MainWindow", "initial savings"))
        self.Financing_subheader.setText(_translate("MainWindow", "Financing:"))
        self.Purchase_subheader.setText(_translate("MainWindow", "Purchase:"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Purchase_Tab), _translate("MainWindow", "Purchase"))
        self.income_Header.setText(_translate("MainWindow", "Income"))
        self.Num_Units.setText(_translate("MainWindow", "Number of Units:"))
        self.Ave_Rent_Unit.setText(_translate("MainWindow", "Average Rent per Unit ($):"))
        self.Total_Rent_Month.setText(_translate("MainWindow", "Total Monthly Rent ($):"))
        self.Other_Income_Month.setText(_translate("MainWindow", "Other Income per Month ($):"))
        self.Total_Income_Month.setText(_translate("MainWindow", "Total Monthly Income ($):"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Income_Tab), _translate("MainWindow", "Income"))
        self.expense_Header.setText(_translate("MainWindow", "Expenses"))
        self.R_and_M_Perc_2.setText(_translate("MainWindow", "Total Fixed Expense ($):"))
        self.Electric.setText(_translate("MainWindow", "Electric ($)"))
        self.Water_and_Sewer.setText(_translate("MainWindow", "Water & Sewer ($)"))
        self.PMI.setText(_translate("MainWindow", "PMI ($)"))
        self.Garbage.setText(_translate("MainWindow", "Garbage ($)"))
        self.HOA.setText(_translate("MainWindow", "HOA ($)"))
        self.Taxes_Monthly.setText(_translate("MainWindow", "Monthly Taxes ($):"))
        self.Insurance.setText(_translate("MainWindow", "Insurance ($)"))
        self.Other_Expenses.setText(_translate("MainWindow", "Other ($)"))
        self.Fixed_Subheader.setText(_translate("MainWindow", "Fixed Expenses:"))
        self.Variable_Subheader.setText(_translate("MainWindow", "Variable Expenses:"))
        self.Total_Var_Expense.setText(_translate("MainWindow", "Total Variable Expenses ($)"))
        self.R_and_M_Perc.setText(_translate("MainWindow", "Repairs & Maint. (%):"))
        self.R_and_M_Doll.setText(_translate("MainWindow", "Repairs & Maint. ($):"))
        self.Cap_Ex_Perc.setText(_translate("MainWindow", "Cap. Ex. (%):"))
        self.Cap_Ex_Doll.setText(_translate("MainWindow", "Cap. Ex. ($):"))
        self.Vacancy_Perc.setText(_translate("MainWindow", "Vacancy (%):"))
        self.Vacancy_Doll.setText(_translate("MainWindow", "Vacancy ($):"))
        self.Management_Perc.setText(_translate("MainWindow", "Management Fee (%):"))
        self.Management_Doll.setText(_translate("MainWindow", "Management Fee ($):"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Expense_Tab), _translate("MainWindow", "Expense"))
        self.assumptions_Header.setText(_translate("MainWindow", "Assumptions"))
        self.Annual_Rent_Appreciation.setText(_translate("MainWindow", "Annual Rent Appreciation (%):"))
        self.Annual_Expense_Appreciation.setText(_translate("MainWindow", "Annual Expense Appreciation (%):"))
        self.Annual_Property_Appreciation.setText(_translate("MainWindow", "Annual Property Appreciation (%):"))
        self.Selling_Costs.setText(_translate("MainWindow", "Selling Costs (%):"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Assumptions_Tab), _translate("MainWindow", "Assumptions"))
        self.report_Header.setText(_translate("MainWindow", "Report"))
        self.Generate_Report.setText(_translate("MainWindow", "Generate Report"))
        self.Tabs.setTabText(self.Tabs.indexOf(self.Report_Tab), _translate("MainWindow", "Report"))
        self.Downpayment_Perc.setText(_translate("MainWindow", "Downpayment (%):"))
        self.Downpayment_Doll.setText(_translate("MainWindow", "Downpayment ($):"))
        self.Loan_Amount.setText(_translate("MainWindow", "Loan Amount ($):"))
        self.Interest_Rate.setText(_translate("MainWindow", "Annual Interest Rate (%):"))
        self.Term.setText(_translate("MainWindow", "Term (years):"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuAbout.setTitle(_translate("MainWindow", "About"))
        self.actionNew.setText(_translate("MainWindow", "New"))
        self.actionLoad.setText(_translate("MainWindow", "Load"))
        self.actionSave.setText(_translate("MainWindow", "Save"))
        self.actionSave_As.setText(_translate("MainWindow", "Save As"))
        self.actionExecute.setText(_translate("MainWindow", "Execute"))
        self.actionSend.setText(_translate("MainWindow", "Send"))
        self.actionClear_All.setText(_translate("MainWindow", "Clear All"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionAbout_REI_Calculator.setText(_translate("MainWindow", "About REI Calculator"))
        self.actionSFI.setText(_translate("MainWindow", "SFI"))

